#!/bin/sh

set -e

sudo bash -c "echo 'LoadModule passenger_module /var/lib/gems/1.9.1/gems/passenger-3.0.19/ext/apache2/mod_passenger.so
PassengerRoot /var/lib/gems/1.9.1/gems/passenger-3.0.19
PassengerRuby /usr/bin/ruby1.9.1
PassengerMaxPoolSize 10
PassengerMinInstances 10
PassengerPoolIdleTime 10' > /etc/apache2/conf.d/passenger"

/etc/init.d/apache2 restart
